
exports('IsActive',    IsFreecamActive)
exports('SetActive',   SetFreecamActive)
exports('IsFrozen',    IsFreecamFrozen)
exports('SetFrozen',   SetFreecamFrozen)
exports('GetFov',      GetFreecamFov)
exports('SetFov',      SetFreecamFov)
exports('GetPosition', GetFreecamPosition)
exports('SetPosition', SetFreecamPosition)
exports('GetRotation', GetFreecamRotation)
exports('SetRotation', SetFreecamRotation)
exports('GetMatrix',   GetFreecamMatrix)
exports('GetTarget',   GetFreecamTarget)

exports('GetPitch', function () return GetFreecamRotation().x end)
exports('GetRoll',  function () return GetFreecamRotation().y end)
exports('GetYaw',   function () return GetFreecamRotation().z end)

exports('GetKeyboardControl', function (key) return _G.KEYBOARD_CONTROL_MAPPING[key]  end)
exports('GetGamepadControl',  function (key) return _G.GAMEPAD_CONTROL_MAPPING[key]   end)
exports('GetKeyboardSetting', function (key) return _G.KEYBOARD_CONTROL_SETTINGS[key] end)
exports('GetGamepadSetting',  function (key) return _G.GAMEPAD_CONTROL_SETTINGS[key]  end)
exports('GetCameraSetting',   function (key) return _G.CAMERA_SETTINGS[key]           end)

exports('SetKeyboardControl', function (key, value) _G.KEYBOARD_CONTROL_MAPPING[key]  = value end)
exports('SetGamepadControl',  function (key, value) _G.GAMEPAD_CONTROL_MAPPING[key]   = value end)
exports('SetKeyboardSetting', function (key, value) _G.KEYBOARD_CONTROL_SETTINGS[key] = value end)
exports('SetGamepadSetting',  function (key, value) _G.GAMEPAD_CONTROL_SETTINGS[key]  = value end)
exports('SetCameraSetting',   function (key, value) _G.CAMERA_SETTINGS[key]           = value end)